### ISSUE TITLE
Error: Module 'ngQuill' is not available

### ISSUE THREAD

**Issue by rafaelrph** [KillerCodeMonkey/ng-quill#132]
Please, what's this error?

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module frontendApp due to:
Error: [$injector:modulerr] Failed to instantiate module ngQuill due to:
Error: [$injector:nomod] Module 'ngQuill' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.3/$injector/nomod?p0=ngQuill
    at http://localhost:8000/bower_components/angular/angular.js:66:12
    at http://localhost:8000/bower_components/angular/angular.js:2257:17
    at ensure (http://localhost:8000/bower_components/angular/angular.js:2178:38)
    at module (http://localhost:8000/bower_components/angular/angular.js:2255:14)
    at http://localhost:8000/bower_components/angular/angular.js:4896:22
    at forEach (http://localhost:8000/bower_components/angular/angular.js:402:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4880:5)
    at http://localhost:8000/bower_components/angular/angular.js:4898:40
    at forEach (http://localhost:8000/bower_components/angular/angular.js:402:20)
    at loadModules (http://localhost:8000/bower_components/angular/angular.js:4880:5)
```

bower.json

```
"ngQuill": "ng-quill#^3.2.0",
"quill-fix": "https://github.com/quilljs/quill/releases/download/v1.1.5/quill.tar.gz"
```

app.js
```
angular.module('app', [... , 'ngQuill'])

.config(ngQuillConfigProvider) {
ngQuillConfigProvider.set({
      modules: {
        toolbar: [['bold', 'italic', 'underline', 'strike'],
                 ['blockquote', 'code-block'],
                 [{ 'list': 'ordered'}, { 'list': 'bullet' }, { 'align': [] }],
                 ['link', 'image']]
               }
    });
}
```

**Comment by KillerCodeMonkey** [comment]
Did you add ngQuill AS dependency to your angular module?

`angular.module('APP', ['ngQuill'])`

Checkout the demo.html

Am 07.11.2017 03:02 schrieb "Rafael Barros" <notifications@github.com>:

**Comment by KillerCodeMonkey** [comment]
yep, and did you added ng-quill as a script tag to your index.html?

or if you have a buildprocess to your buildprocess?

**Comment by rafaelrph** [comment]
Yes... I added as a script.

<script></script>
<script src="bower_components/quill-fix/quill.js"></script>
<script src="bower_components/ngQuill/dist/ng-quill.min.js"></script>


Yes, I have a grunt build process to compile and build the project.

**Comment by KillerCodeMonkey** [comment]
there should not be a dist-folder for bower.

Checkout latest version from this morning. the base file path of bower should be /src/ng-quill.js

**Comment by KillerCodeMonkey** [comment]
did you solve the problem?

**Comment by rafaelrph** [comment]
I haven't tried yet... When I try, I'll let you know if everything is okay.
Thanks again

**Comment by KillerCodeMonkey** [comment]
any updates?

**Comment by KillerCodeMonkey** [comment]
closed due to inactivity.
